/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/features/**/*.{js,ts,jsx,tsx}",
    "./src/shared/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#484847",
        "on-error": "#490013",
        "on-tertiary-fixed-variant": "#006a2d",
        "on-secondary-fixed": "#443100",
        "surface-container-highest": "#262626",
        "surface-container-high": "#201f1f",
        "primary-fixed": "#c284ff",
        "primary": "#cc97ff",
        "on-tertiary": "#00692c",
        "on-secondary": "#574000",
        "tertiary-container": "#6bff8f",
        "surface-container-lowest": "#000000",
        "on-primary-fixed": "#000000",
        "background": "#0e0e0e",
        "on-tertiary-fixed": "#004a1d",
        "on-secondary-fixed-variant": "#674d00",
        "error-container": "#a70138",
        "on-primary-fixed-variant": "#430076",
        "on-primary-container": "#360061",
        "inverse-on-surface": "#565555",
        "surface": "#0e0e0e",
        "on-surface": "#ffffff",
        "tertiary-fixed-dim": "#5bf083",
        "on-error-container": "#ffb2b9",
        "on-secondary-container": "#fff6ec",
        "surface-variant": "#262626",
        "surface-dim": "#0e0e0e",
        "tertiary-fixed": "#6bff8f",
        "on-background": "#ffffff",
        "surface-bright": "#2c2c2c",
        "inverse-primary": "#842cd3",
        "error-dim": "#d73357",
        "on-primary": "#47007c",
        "tertiary-dim": "#5bf083",
        "error": "#ff6e84",
        "tertiary": "#c5ffc9",
        "secondary-fixed": "#ffca45",
        "secondary": "#fdc425",
        "primary-dim": "#9c48ea",
        "on-tertiary-container": "#005f28",
        "primary-container": "#c284ff",
        "on-surface-variant": "#adaaaa",
        "surface-container-low": "#131313",
        "primary-fixed-dim": "#b971ff",
        "outline": "#777575",
        "secondary-container": "#785a00",
        "secondary-dim": "#edb60f",
        "surface-container": "#1a1919",
        "inverse-surface": "#fcf9f8",
        "secondary-fixed-dim": "#f3bb19",
        "surface-tint": "#cc97ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-jakarta)"],
        body: ["var(--font-jakarta)"],
        label: ["var(--font-jakarta)"],
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
